"""
Combine the three transfer-robustness figures (grid-cliff, acrobot, lander)
into a single 1x3 figure with a shared legend.

Output: figures/transfer_combined.png (and .pdf)
Run from repo root:  python scripts/plot_combined_transfer.py
"""
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from matplotlib.offsetbox import AnnotationBbox, OffsetImage
from PIL import Image

from mavrl_experiments.utils import compute_aggregated_metric, load_experiment_data
from mavrl.visualization.feedback_palettes import FEEDBACK_PALETTE, HUE_ORDER_SELECTED
ICON_DIR = REPO_ROOT / "results" / "figures" / "fb_combo_tags_png"
NORM_PATH = REPO_ROOT / "results" / "normalization_values.json"
OUT_DIR = REPO_ROOT / "results" / "figures"

# New fixalloc queues (non-imitation rows). Generated by
# scripts/enqueue_transfer.py + scripts/launch_transfer_fixalloc.sh.
EXPERIMENTS_DIR = REPO_ROOT / "experiments"
NEW_QUEUES = {
    "grid_cliff":      EXPERIMENTS_DIR / "transfer_fixalloc_grid_cliff",
    "grid_trap":       EXPERIMENTS_DIR / "transfer_fixalloc_grid_trap",
    "acrobot_v1":      EXPERIMENTS_DIR / "transfer_fixalloc_acrobot_v1",
    "lunar_lander_v3": EXPERIMENTS_DIR / "transfer_fixalloc_lunar_lander_v3",
}
# Old queues only used for the unchanged imitation row.
OLD_QUEUES = {
    "grid_cliff":      EXPERIMENTS_DIR / "transfer_grid_cliff_25012026",
    "grid_trap":       EXPERIMENTS_DIR / "transfer_grid_trap_25012026",
    "acrobot_v1":      EXPERIMENTS_DIR / "transfer_acrobot_27012026_new_imit",
    "lunar_lander_v3": EXPERIMENTS_DIR / "transfer_lander_24012026",
}

COMBOS_TO_KEEP = [
    "demo+pref+rating+stop",
    "demo_only",
    "pref_only",
    "rating_only",
    "imitation",
    "stop_only",
]

ICON_NAME_MAP = {
    "demo+pref": "pref+demo",
    "demo+pref+rating+stop": "pref+demo+rating+stop",
}

# Readable font sizes (tuned for ~ \textwidth*0.95 in a two-column paper).
LABEL_FS = 22
TICK_FS = 18
TITLE_FS = 24
ANNOT_FS = 16


def load_icon(feedback_combo: str) -> Image.Image:
    icon_name = ICON_NAME_MAP.get(feedback_combo, feedback_combo)
    return Image.open(ICON_DIR / f"{icon_name}.png")


def _dashes_map():
    m = {fb: "" for fb in COMBOS_TO_KEEP}
    m["imitation"] = (5, 2)
    return m


def _load_two_queues(env_key: str) -> pd.DataFrame:
    """Load new fixalloc queue + the imitation row from the old queue.

    Skips a queue silently if its directory is missing. This lets you preview
    the figure with old data before the new fixalloc queue is populated.
    """
    pieces = []
    new_q = NEW_QUEUES[env_key]
    if new_q.exists():
        df_new = load_experiment_data(new_q)
        if not df_new.empty:
            df_new = df_new[df_new["config.feedback_combo"] != "imitation"]
            pieces.append(df_new)
    else:
        print(f"  (skipping non-existent new queue {new_q})", file=sys.stderr)

    old_q = OLD_QUEUES[env_key]
    if old_q.exists():
        df_old = load_experiment_data(old_q)
        if not df_old.empty:
            df_imit = df_old[df_old["config.feedback_combo"] == "imitation"]
            pieces.append(df_imit)
            if not pieces[:-1]:  # nothing from new queue yet — fall back fully
                pieces[-1] = df_old
                print(f"  (new queue empty — falling back to OLD queue {old_q} for all rows)",
                      file=sys.stderr)
    else:
        print(f"  (skipping non-existent old queue {old_q})", file=sys.stderr)

    if not pieces:
        return pd.DataFrame()
    return pd.concat(pieces, ignore_index=True)


def _prep_grid_cliff() -> pd.DataFrame:
    return _prep_grid("grid_cliff")


def _prep_grid_trap() -> pd.DataFrame:
    return _prep_grid("grid_trap")


def _prep_grid(env_key: str) -> pd.DataFrame:
    """Shared loader for tabular grid envs (cliff, trap). x-axis = p_rand."""
    df = _load_two_queues(env_key)
    df["discounted_value"] = compute_aggregated_metric(df, "discounted_value", "max")
    norm = json.load(open(NORM_PATH))[env_key]
    df["y"] = 100 * (
        (df["discounted_value"] - norm["uniform_discounted_value"])
        / (norm["optimal_discounted_value"] - norm["uniform_discounted_value"])
    )
    df = df[
        df["config.feedback_combo"].isin(COMBOS_TO_KEEP)
        & (df["config.env_params.p_rand"] <= 0.8)
    ].copy()
    df["x"] = df["config.env_params.p_rand"]
    return df


def _prep_acrobot() -> pd.DataFrame:
    df = _load_two_queues("acrobot_v1")
    df["mean_reward"] = compute_aggregated_metric(df, "mean_reward", "max")
    norm = json.load(open(NORM_PATH))["Acrobot-v1"]
    df["y"] = 100 * (
        (df["mean_reward"] - norm["uniform_mean_return"])
        / (norm["optimal_mean_return"] - norm["uniform_mean_return"])
    )
    df = df[df["config.feedback_combo"].isin(COMBOS_TO_KEEP)].copy()
    df["x"] = df["config.env_params.asymmetry"]
    return df


def _prep_lander():
    df = _load_two_queues("lunar_lander_v3")
    df["mean_reward"] = compute_aggregated_metric(df, "mean_reward", "max")
    norm = json.load(open(NORM_PATH))["LunarLander-v3"]
    df["y"] = 100 * (
        (df["mean_reward"] - norm["uniform_mean_return"])
        / (norm["optimal_mean_return"] - norm["uniform_mean_return"])
    )
    df.fillna({"config.env_params.wind_power": 0}, inplace=True)
    df = df[df["config.feedback_combo"].isin(COMBOS_TO_KEEP)].copy()

    df_baseline = df[
        (df["config.env_params.gravity"] == -10.0)
        & (df["config.env_params.wind_power"] == 0.0)
    ].copy()
    df_inter = df[
        (df["config.env_params.gravity"] == -11.0)
        & (df["config.env_params.wind_power"] == 0.0)
    ].copy()
    df_high = df[df["config.env_params.gravity"] == -11.9].copy()

    wind_values = sorted(df_high["config.env_params.wind_power"].unique())
    df_baseline["x"] = 0
    df_inter["x"] = 1
    df_high["x"] = df_high["config.env_params.wind_power"].map(
        {w: i + 2 for i, w in enumerate(wind_values)}
    )
    df_out = pd.concat([df_baseline, df_inter, df_high], ignore_index=True)

    x_ticks = [0, 1] + list(range(2, 2 + len(wind_values)))
    wind_labels = []
    for i, w in enumerate(wind_values):
        w_str = f"w={w:.1f}" if w != int(w) else f"w={int(w)}"
        if i == 0:
            wind_labels.append(f"g=-12\n{w_str}")
        else:
            wind_labels.append(w_str)
    x_tick_labels = ["g=-10\nw=0", "g=-11\nw=0"] + wind_labels
    return df_out, x_ticks, x_tick_labels, len(wind_values)


def _draw_line(ax, df, xlabel, title):
    sns.lineplot(
        data=df,
        x="x",
        y="y",
        hue="config.feedback_combo",
        style="config.feedback_combo",
        palette=FEEDBACK_PALETTE,
        dashes=_dashes_map(),
        hue_order=COMBOS_TO_KEEP,
        linewidth=3.2,
        errorbar="se",
        ax=ax,
        legend=False,
    )
    ax.set_xlabel(xlabel, fontsize=LABEL_FS)
    ax.set_title(title, fontsize=TITLE_FS)
    ax.tick_params(axis="both", labelsize=TICK_FS, colors="black", width=1.2)
    sns.despine(ax=ax)
    # Make the left/bottom spines clearly visible black lines.
    for side in ("left", "bottom"):
        ax.spines[side].set_color("black")
        ax.spines[side].set_linewidth(1.2)


def main():
    sns.set_style("whitegrid")
    plt.rcParams["font.family"] = "serif"
    plt.rcParams["font.serif"] = ["Times New Roman", "Times", "DejaVu Serif"]
    plt.rcParams["mathtext.fontset"] = "stix"

    df_cliff = _prep_grid_cliff()
    df_trap  = _prep_grid_trap()
    df_acro  = _prep_acrobot()
    df_lander, x_ticks_l, x_labels_l, n_wind = _prep_lander()

    fig, axes = plt.subplots(
        1, 4, figsize=(22, 5.2), gridspec_kw={"wspace": 0.12}
    )

    _draw_line(axes[0], df_cliff, "Environment stochasticity", "Grid-Cliff")
    axes[0].set_ylabel("Normalized return", fontsize=LABEL_FS)

    _draw_line(axes[1], df_trap, "Environment stochasticity", "Grid-Trap")
    axes[1].set_ylabel("")

    _draw_line(axes[2], df_acro, "Link length asymmetry", "Acrobot")
    axes[2].set_ylabel("")

    _draw_line(axes[3], df_lander, "Wind power and gravity", "Lunar-Lander")
    axes[3].set_ylabel("")
    axes[3].set_xticks(x_ticks_l)
    axes[3].set_xticklabels(x_labels_l, fontsize=TICK_FS - 3)
    axes[3].axvline(x=2.5, color="gray", linestyle="--", alpha=0.5, linewidth=1)
    ylim = axes[3].get_ylim()
    y_text = ylim[0] + 0.04 * (ylim[1] - ylim[0])
    axes[3].text(0.5, y_text, "gravity only", ha="center",
                 fontsize=ANNOT_FS, style="italic")
    axes[3].text(
        (2 + n_wind - 1) / 2 + 1, y_text,
        "g=-12, varying wind", ha="center", fontsize=ANNOT_FS, style="italic",
    )

    # Shared icon legend, clustered in the center above the subplots.
    n_items = len(HUE_ORDER_SELECTED)
    zoom = 0.085
    y_legend = 0.93
    spacing = 0.055  # in figure fraction
    x_center = 0.51
    x_start = x_center - (n_items - 1) * spacing / 2
    for i, fb in enumerate(HUE_ORDER_SELECTED):
        try:
            img = load_icon(fb)
        except FileNotFoundError:
            continue
        ab = AnnotationBbox(
            OffsetImage(img, zoom=zoom),
            (x_start + i * spacing, y_legend),
            xycoords="figure fraction",
            frameon=False,
            box_alignment=(0.5, 0.5),
        )
        fig.add_artist(ab)

    fig.subplots_adjust(top=0.82, bottom=0.18, left=0.06, right=0.99)

    OUT_DIR.mkdir(exist_ok=True)
    out_png = OUT_DIR / "transfer_combined.png"
    out_pdf = OUT_DIR / "transfer_combined.pdf"
    fig.savefig(out_png, dpi=300, bbox_inches="tight")
    fig.savefig(out_pdf, bbox_inches="tight")
    print(f"Saved: {out_png}\nSaved: {out_pdf}")


if __name__ == "__main__":
    main()
